" " " TODO: "
"dataset_config is a pointer file to the Azure Blob's version control"
"In order to have integrated VC in our repo you need to..."
"- zip the UCF_Crime Files into one file"
"Enable VC on azure blob"
"- grab the VID of the zip file"
"Complete dataset config scripting "
"update test_env.py to include a method for fetching the current dataset version & desc."
"" " "