" " " TODO:"
"Main Focus -> Inference & Audit Pipeline "
"An Inference is the process of running live data through a trained AI model to make a prediction or solve a task."
"Audit is just checking it's validity in a real world context"
"- Finish Configuring Label Studio"
"- Fetch Data from the internet & integrate to Azure Blob"
"- Annontate Data with Label Studio"
"- Train Model"
"Audit Model"
"Report Results"
""
