task: detect
model: yolov8n.pt
teacher_model: ../../runs/detect/train13/weights/best.pt
data: data.yaml
dataset_url: https://drive.google.com/drive/folders/1JkrofKsIqaIjhham4fHx9ba0hxHar76p?usp=sharing
epochs: 75
imgsz: 640
batch: 16
optimizer: auto
patience: 20
project: ../../runs/detect
name: roboflow_distill
exist_ok: true
distill_temperature: 2.0
distill_cls_weight: 0.5
distill_box_weight: 0.25
